version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    image: event/catalogapi
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDB
      DatabaseUser: sa
      DatabaseUserPassword: ProductApi(!)
      ExternalCatalogBaseUrl: http://localhost:60900
    ports:
      - "60900:80"
    container_name: catalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: event/cartapi
    environment: 
      IdentityUrl: http://10.0.0.182:5070
      ConnectionString: basket.data
    ports:
      - "5065:80"
    container_name: cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - frontend
      - backend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: event/orderapi
    environment: 
      IdentityUrl: http://10.0.0.182:5070
      SQLSERVER_HOST: catalogdb
      SA_PASSWORD: ProductApi(!)
      DATABASE: OrdersDb
    ports:
      - "5075:80"
    container_name: orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq

  webmvc:
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    image: event/webmvc
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://10.0.0.182:5070
      CallBackUrl: http://localhost:5202
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_8cW1zkgPV8l0zPeZByUIbjlv00f4wBKo8S
      StripePrivateKey: sk_test_dMb2aqnw7cJ3QpFUnSfsLXLo00WoyBIoXx
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5202:80"
    container_name: webshop
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - frontend
    depends_on:
      - catalog
      - tokenserver
      - cart
      - order

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    container_name: catalogdb
    ports:
      - "1448:1433"
    networks:
      - backend

  basket.data:
    image: redis
    ports:
      - "6378:6379"
    networks:
      - backend

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: event/tokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5202     
    ports:
      - "5070:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 

 



